CREATE TABLE ONLINE_PAYMENT (
  ID                VARBINARY(16) NOT NULL,
  VERSION           NUMERIC(8)    NOT NULL DEFAULT 1,
  AMOUNT            NUMERIC(8, 2) NOT NULL,
  STATUS            NUMERIC(2)    NOT NULL,
  CORRELATION_KEY   VARCHAR(32)   NOT NULL,
  CORRELATION_VALUE VARBINARY(16) NOT NULL,
  METHOD            VARCHAR(32)   NOT NULL,
  CREATED_AT        DATETIME      NOT NULL,
  LAST_MODIFIED_AT  DATETIME      NOT NULL,
  CONSTRAINT PK_ONLINE_PAYMENT PRIMARY KEY (ID)
);